### ISSUE TITLE
Make fastlane structures for F-Droid

### ISSUE THREAD

**Issue by Wv5twkFEKh54vo4tta9yu7dHa3** [H-PixelDroid/PixelDroid#179]
This will enable nice metadata in F-Droid, including screenshots and changelogs, etc. See: https://gitlab.com/snippets/1895688

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
I don't think this requires any programming, and we would welcome a PR for this. If you make screenshots, make sure they are taken with demo mode enabled and with only non-copyrighted material in them (easiest would be to take some CC0 photos and post them or whatever)

**Comment by ahangarha** [comment]
I try to learn and do it

**Comment by ahangarha** [comment]
Please share screenshot. Otherwise, I use screenshots I made myself

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Try to make screenshots (I don't have any good ones), try to avoid including photos that aren't under a permissive license like CC0 or some other CC license

**Comment by ahangarha** [comment]
Ok. I use my own profile to be sure there is no issue with copyright
