### ISSUE TITLE
Bad camera layout in RTL mode

### ISSUE THREAD

**Issue by ahangarha** [H-PixelDroid/PixelDroid#180]
In RTL layout, the camera layout has wrong padding/margin. See this screenshot:

![Screenshot_۲۰۲۰۰۵۱۹-۱۴۱۹۰۳](https://user-images.githubusercontent.com/11241315/82315850-325f0200-99e1-11ea-8f8d-e34f9f74fb58.png)

tested on ` v1.0.alpha1` on 379b2c9

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Thank you for reporting! I have looked at this a little bit, but I have no clue what is causing this yet. If someone wants to try debugging this, I would welcome it.
