### ISSUE TITLE
No "publish" option when editing photo in dark mode

### ISSUE THREAD

**Issue by retiolus** [H-PixelDroid/PixelDroid#183]
Lineage OS 17.1 / 6.18 inches 

![image](https://user-images.githubusercontent.com/65604466/82327698-135f7080-99df-11ea-94ba-ed595622f69b.png)

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Right, forgot to fix this. Shouldn't take too long. Thanks for the report. (in the meantime, switch to light mode)

**Comment by retiolus** [comment]
Light mode? I do not see any options to change to light or dark mode...

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
@retiolus there are settings you can access from the drawer. Maybe we should make it clearer that there is a drawer :sweat_smile:

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
The buttons are now invisible in light mode, so I'm reopening this.
