### ISSUE TITLE
Cannot connect to my account

### ISSUE THREAD

**Issue by dnno** [H-PixelDroid/PixelDroid#188]
I just downloaded the alpha version, but I cannot connect tonmy account @pixelfed.social. after the authentication and permission screen, the app just hangs with a spinner. Screenshot attached, not sure what additional information I can give. Might 2FA be a problem?

![Screenshot_20200519-203026](https://user-images.githubusercontent.com/2003552/82364829-19217a00-9a10-11ea-894f-a77c0e6ec6a6.jpg)

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Yes, 2FA is the problem. Dansup is on it :)
This was mentioned in the release notes.
