### ISSUE TITLE
Constrast and saturation bars seem to be switched

### ISSUE THREAD

**Issue by Dobios** [H-PixelDroid/PixelDroid#195]
* [x] I checked the release notes for known issues
* [x] I checked the existing issues
* [x] I checked that the issue is not related to my instance configuration, and that my instance has the latest version of pixelfed.

When editing a photo in the pixeldroid editor, the contrast bar seems to change the photo's saturation and vice-versa.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Was a typo, both contrast and saturation were hooked up to the saturation listener
