### ISSUE TITLE
Prevent repeated posts of the same content

### ISSUE THREAD

**Issue by stensonb** [H-PixelDroid/PixelDroid#200]
When posting, there is no feedback to the user that it is "in progress"...which made me think I had to press "submit" again, and again, and again.

And now I have 16 posts of the same picture.  :)

As a user, I should be prevented from posting the same image repeatedly...or at least promoted with a confirmation dialog.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
This is addressed in #191, which will probably be merged in the next alpha. We know that there is a lot of work needed in the whole upload process, and it is something we're working on. Thank you for your report!
