### ISSUE TITLE
nouvelles librairies pas updatable

### ISSUE THREAD

**Issue by ulysse42** [H-PixelDroid/PixelDroid#207]
https://github.com/H-PixelDroid/PixelDroid/blob/f95f72aeae2bb38af8af604ce551f550cf52e190/app/build.gradle#L127

la lib citée ci-dessus n'est pas à jour, et la mettre à jour fait crash l'app.
Plus spécifiquement, l'import `import com.mikepenz.iconics.typeface.library.googlematerial.GoogleMaterial` dans le MainActivity n'est plus valable et le nouvel import pour `GoogleMaterial` fait planter un truc, mais j'ai pas plus dig que ça.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Si je me rappelle bien la proposition de Android Studio n'est pas juste, elle essaye de faire mettre à jour vers une version non-kotlin

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
> A newer version of com.mikepenz:google-material-typeface than 3.0.1.4.original-kotlin is available: 3.0.1.3.original

clairement pas ce qu'on veut ça, c'est ça que tu veux dire?

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
En vérifiant sur maven, 3.0.1.4 est bien la dernière version.

**Comment by ulysse42** [comment]
ah oui my bad Android Studio mongolise, il me propose 3.0.1.2 enfaite
