### ISSUE TITLE
As a user I would like to have an offline mode with cached posts

### ISSUE THREAD

**Issue by Sanimys** [H-PixelDroid/PixelDroid#36]

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
I'll take a look at this now, maybe a fresh pair of eyes can help.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
An example of usage of a Room database with an infinite scroll: https://gitlab.epfl.ch/debeule/paginwithnetworksamplesimplified
