### ISSUE TITLE
PRs naming and issues

### ISSUE THREAD

**Issue by samuelchassot** [H-PixelDroid/PixelDroid#38]
Hi everyone,

just a little message to ask you to:
- link the PR you open to the issue in which you assign yourself in the sprint backlog
- at least name it the same way
- open it yourself
- if possible, try to commit on a branch if and only if it is yours, you are supposed to work each on the entire piece of functionality

That could be great :)
That would allow us to better track the work you do each week.

Thanks a lot!

**Comment by ulysse42** [comment]
ack
